server.port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring2023
    username: postgres
    password: 123
  sql.init.mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active: development

---
spring.config.activate.on-profile: development
---

spring.config.activate.on-profile: debug
server.port: 2004
spring.datasource.url: jdbc:postgresql://localhost:5432/spring2023Test
